<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- Optional: disable native app host generation. The application will run using "dotnet MyApp.dll". -->
		<UseAppHost>false</UseAppHost>
	</PropertyGroup>

</Project>
