<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- Optional: disable native app host generation. The application will run using "dotnet MyApp.dll". -->
		<UseAppHost>false</UseAppHost>


	

    <IsPackable>true</IsPackable>
    
    <PackageId>TailwindRazorPage</PackageId>
    <Version>0.1.0</Version>
    <PackageIcon>Logo.png</PackageIcon>

	<Authors>NID BOUBKER Houssine</Authors>
    <Description>Modern ASP.NET Core starter templates with Tailwind CSS 4.3, PostCSS, and esbuild for Razor Pages, MVC, Blazor, and .NET MAUI..</Description>
   <PackageTags>asp-net-core;asp-net-core-mvc;asp-net-mvc; aspnetcore;blazor;template;css;dotnet;esbuild;front-end;maui;mvc;postcss;razor-pages;starter-template;tailwindcss;web-development</PackageTags>
    <RepositoryUrl>https://github.com/hnidboubker/aspnetcore-tailwind</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- XML documentation -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<UpToDateCheckBuilt Include="wwwroot/css/app.css" Set="Css" />
		<UpToDateCheckBuilt Include="postcss.config.js" Set="Css" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hasim" Version="0.1.3" />
		<PackageReference Include="Hasim.Core" Version="0.1.0" />
		<PackageReference Include="Hasim.EntityFrameworkCore" Version="0.1.1" />
		<PackageReference Include="Hasim.Injectify" Version="0.1.2" />
		<PackageReference Include="Hasim.Auditify" Version="0.1.5" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.29" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.29" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.29" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.29" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.29">
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	    <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.29" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.29">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TailwindIdentity.EntityFrameworkCore\TailwindIdentity.EntityFrameworkCore.csproj" />
	</ItemGroup>

	<Target Name="Tailwind" BeforeTargets="Build">
		<Exec Command="npm run css:build" />
	</Target>

	   <ItemGroup>
      <None Include="../../assets/images/Logo.png" Pack="true" PackagePath="\" />
  	</ItemGroup>

	<ItemGroup>
  <None Include="README.md" Pack="true" PackagePath="\" />
</ItemGroup>

</Project>
