//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using TailwindRazorPage.Web.Persistence;

//#nullable disable

//namespace TailwindRazorPage.Web.Migrations
//{
//    [DbContext(typeof(DefaultContext))]
//    partial class DefaultContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.24")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Hasim.Core.Entities.AppRole", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Name")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedName")
//                        .IsUnique()
//                        .HasDatabaseName("RoleNameIndex")
//                        .HasFilter("[NormalizedName] IS NOT NULL");

//                    b.ToTable("AspNetRoles", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppRoleClaim", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("RoleId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetRoleClaims", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUser", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("AccessFailedCount")
//                        .HasColumnType("int");

//                    b.Property<string>("ConcurrencyStamp")
//                        .IsConcurrencyToken()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<bool>("EmailConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("LockoutEnabled")
//                        .HasColumnType("bit");

//                    b.Property<DateTimeOffset?>("LockoutEnd")
//                        .HasColumnType("datetimeoffset");

//                    b.Property<string>("NormalizedEmail")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NormalizedUserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("PasswordHash")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("PhoneNumberConfirmed")
//                        .HasColumnType("bit");

//                    b.Property<string>("PictureContentType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<byte[]>("PictureData")
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("PictureUrl")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("SecurityStamp")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("TwoFactorEnabled")
//                        .HasColumnType("bit");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.HasKey("Id");

//                    b.HasIndex("NormalizedEmail")
//                        .HasDatabaseName("EmailIndex");

//                    b.HasIndex("NormalizedUserName")
//                        .IsUnique()
//                        .HasDatabaseName("UserNameIndex")
//                        .HasFilter("[NormalizedUserName] IS NOT NULL");

//                    b.ToTable("User", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserClaim", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("ClaimType")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("ClaimValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("UserId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserClaims", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserLogin", b =>
//                {
//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderKey")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("ProviderDisplayName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("UserId")
//                        .HasColumnType("int");

//                    b.HasKey("LoginProvider", "ProviderKey");

//                    b.HasIndex("UserId");

//                    b.ToTable("AspNetUserLogins", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserRole", b =>
//                {
//                    b.Property<int>("UserId")
//                        .HasColumnType("int");

//                    b.Property<int>("RoleId")
//                        .HasColumnType("int");

//                    b.HasKey("UserId", "RoleId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("AspNetUserRoles", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserToken", b =>
//                {
//                    b.Property<int>("UserId")
//                        .HasColumnType("int");

//                    b.Property<string>("LoginProvider")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Name")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Value")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("UserId", "LoginProvider", "Name");

//                    b.ToTable("AspNetUserTokens", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AuditLog", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Action")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("CorrelationId")
//                        .HasMaxLength(128)
//                        .HasColumnType("nvarchar(128)");

//                    b.Property<string>("EntityName")
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("IpAddress")
//                        .HasMaxLength(45)
//                        .HasColumnType("nvarchar(45)");

//                    b.Property<DateTime>("Timestamp")
//                        .HasColumnType("datetime2");

//                    b.Property<int?>("UserId")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.HasIndex("Timestamp");

//                    b.HasIndex("UserId");

//                    b.ToTable("AuditLog", (string)null);
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.EntityChange", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<int>("AuditLogId")
//                        .HasColumnType("int");

//                    b.Property<string>("EntityName")
//                        .IsRequired()
//                        .HasMaxLength(256)
//                        .HasColumnType("nvarchar(256)");

//                    b.Property<string>("NewValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("OldValue")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("PropertyName")
//                        .IsRequired()
//                        .HasMaxLength(128)
//                        .HasColumnType("nvarchar(128)");

//                    b.HasKey("Id");

//                    b.HasIndex("AuditLogId");

//                    b.ToTable("EntityChange", (string)null);
//                });

//            modelBuilder.Entity("TailwindRazorPage.Web.Persistence.Models.EmailMessage", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Body")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime>("CreatedAt")
//                        .HasColumnType("datetime2");

//                    b.Property<string>("ErrorMessage")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("From")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<bool>("IsHtml")
//                        .HasColumnType("bit");

//                    b.Property<DateTime?>("SentAt")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("Status")
//                        .HasColumnType("int");

//                    b.Property<string>("Subject")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("To")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.ToTable("EmailMessages");
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppRoleClaim", b =>
//                {
//                    b.HasOne("Hasim.Core.Entities.AppRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserClaim", b =>
//                {
//                    b.HasOne("Hasim.Core.Entities.AppUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserLogin", b =>
//                {
//                    b.HasOne("Hasim.Core.Entities.AppUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserRole", b =>
//                {
//                    b.HasOne("Hasim.Core.Entities.AppRole", null)
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("Hasim.Core.Entities.AppUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AppUserToken", b =>
//                {
//                    b.HasOne("Hasim.Core.Entities.AppUser", null)
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AuditLog", b =>
//                {
//                    b.HasOne("Hasim.Core.Entities.AppUser", "User")
//                        .WithMany()
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Restrict);

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.EntityChange", b =>
//                {
//                    b.HasOne("Hasim.Core.Entities.AuditLog", "AuditLog")
//                        .WithMany("EntityChanges")
//                        .HasForeignKey("AuditLogId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("AuditLog");
//                });

//            modelBuilder.Entity("Hasim.Core.Entities.AuditLog", b =>
//                {
//                    b.Navigation("EntityChanges");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
